#!/usr/bin/env make

LC   = latexmk
OPT  = -lualatex
COPT = -c

texname = {{texfilename}}
texfile = tex/$(texname).tex

.PHONY : all clean

all: 
	$(LC) $(OPT) $(texfile)

clean:
	# Clear biber cache
	rm -rf `biber --cache`
	# Clear local supplementary files
	$(LC) $(COPT) $(texfile)
